# Generated by Django 5.2.8 on 2025-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANS', 'Transportation'), ('HOUS', 'Housing'), ('UTIL', 'Utilities'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
